### ISSUE TITLE
Columns on full width container issue

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#15]
https://revamp--sunstar-foundation--sunstar-foundation.hlx.page/en/awards

For some reasons the image doesn't fill the whole container.
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/fb84b401-40e3-412e-b0ef-0fe957d5a136)
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/ac9e2305-b6e2-4499-be99-dfb365087786)

Can you also please create a variant for max-width for text-col to limit the size of the text container when we have full width columns?

Something like this:
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/67d7a951-89a4-4173-aaf9-fb074b763672)

This is the wanted outcome:
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/27e43f55-3cac-432a-a8d4-55cd0f8e6409)

@bosschaert @sdmcraft

**Comment by shrotia** [comment]
> Can you also please create a variant for max-width for text-col to limit the size of the text container when we have full width columns?

For this specific ask, I am raising another PR. 

Meanwhile, you can review and approve the following PR for the original issue:
https://github.com/sunstar-foundation/sunstar-foundation/pull/29

**Comment by shrotia** [comment]
@ehrro The Columns (splits) variant already exist [0], though it stopped working due to a conflicting change. I have restored it. 

Please have a look at [1] [2] and confirm if it serves the purpose. Thank you
CC: @bosschaert 

[0] https://github.com/hlxsites/sunstar-foundation/pull/6
[1] https://issue-5--sunstar-foundation--hlxsites.hlx.page/drafts/dbute/flex-cols
[2] https://issue-15-v2--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/columns&index=19

**Comment by ehrro** [comment]
I added some more logic for the padding on mobile and merged the pr. Thank you @shrotia .
