### ISSUE TITLE
Tabs component not working

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#44]
We have an issue with the tab block

https://main--sunstar-foundation--sunstar-foundation.hlx.page/grants/received-list
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/a7b1f8ea-135f-4984-9f40-a8551df760eb)

@bosschaert @meejain @sdmcraft

**Comment by meejain** [comment]
Many Thanks @JiangLong2019 for taking this. 

cc @ehrro

**Comment by JiangLong2019** [comment]
Hi @ehrro , the issue has been fixed by authoring, you can have a check. 

For details:
You can see the tabs in "hero-horizontal-tabs" block which need to set to each Section Metadata with the same name. Program use this id to separate different tab contents.

<img width="659" alt="image" src="https://github.com/sunstar-foundation/sunstar-foundation/assets/57093988/09b109f3-1f4b-492a-97ab-e071bc84b340">

<img width="623" alt="image" src="https://github.com/sunstar-foundation/sunstar-foundation/assets/57093988/953aa919-3426-40e0-96bc-12898dc56b56">

**Comment by ehrro** [comment]
Thank you @JiangLong2019 but what exactly did you change? I checked and it looked properly implemented. I compared it with the implementation on sunstar.com and saw nothing wrong. I also changed the - (because in Word sometimes it adds different - in some cases).

**Comment by ehrro** [comment]
Thank you @JiangLong2019
